config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, only: :sessions
  resources :guests
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :index
  root 'index#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)

    return if user.id.nil?

    can :access, :rails_admin   # grant access to rails_admin
    can :read, :dashboard       # grant access to the dashboard

    if user.admin?
      can :manage, :all
    elsif user.guest?
      can :read, :all
      # can :manage, User, id: user.id
      # can :manage, Message, user_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/guest.rb
class Guest < ApplicationRecord
end

app/models/history.rb
class History < ApplicationRecord
end

app/models/honour.rb
class Honour < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: %i[guest admin]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  before_action :set_guest, only: [:show, :edit, :update, :destroy]
  
  # GET /guests
  # GET /guests.json
  def index
    if params[:guest][:name].size > 3
      @guests = Guest.where('unaccent(name) ILIKE unaccent(?) AND confirmed IS ?', "#{params[:guest][:name]}%", false).limit(3) if params[:guest].present?
    else
      @guests = []
    end

    respond_to :html, :js
    respond_to do |format|
      format.html
      format.js { render 'guests_table.js.erb' }
    end
  end

  # GET /guests/1
  # GET /guests/1.json
  def show
  end

  # GET /guests/new
  def new
    @guest = Guest.new
  end

  # GET /guests/1/edit
  def edit
  end

  # POST /guests
  # POST /guests.json
  def create
    @guest = Guest.new(guest_params)

    respond_to do |format|
      if @guest.save
        format.html { redirect_to @guest, notice: 'Guest was successfully created.' }
        format.json { render :show, status: :created, location: @guest }
      else
        format.html { render :new }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guests/1
  # PATCH/PUT /guests/1.json
  def update
    if @guest.update(guest_params)
      render js: "setTimeout(function(){$('#edit_guest_#{@guest.id} .confirm-guest').attr({value: 'Confirmado',disabled: ''})},100);"
    end
  end

  # DELETE /guests/1
  # DELETE /guests/1.json
  def destroy
    @guest.destroy
    respond_to do |format|
      format.html { redirect_to guests_url, notice: 'Guest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guest
      @guest = Guest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guest_params
      params.require(:guest).permit(:name, :confirmed)
    end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
    @data = {
      histories: History.all.order(:date),
      honours:   Honour.all
    }
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  layout "devise", only: [:new]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
  def guests_table(guests)
    content_tag :table do
      guests.each do |guest|
        concat content_tag(
          :tr,
          content_tag(
            :td,
            (form_for guest, remote: true do |f|
              cell_content = guest.name
              cell_content << (f.hidden_field :confirmed, value: "true")
              cell_content << f.submit('Confirmar', class: 'confirm-guest btn right')
              cell_content.html_safe
            end)
          )
        )
      end
    end
  end
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/guests/_form.html.erb
<%= form_with(model: guest, local: true) do |form| %>
  <% if guest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(guest.errors.count, "error") %> prohibited this guest from being saved:</h2>

      <ul>
      <% guest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :confirmed %>
    <%= form.check_box :confirmed %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/guests/_list.html.erb
<p id="notice"><%= notice %></p>

<h1>Guests</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Confirmed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @guests.each do |guest| %>
      <tr>
        <td><%= guest.name %></td>
        <td><%= guest.confirmed %></td>
        <td><%= link_to 'Show', guest %></td>
        <td><%= link_to 'Edit', edit_guest_path(guest) %></td>
        <td><%= link_to 'Destroy', guest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Guest', new_guest_path %>

app/views/guests/edit.html.erb
<h1>Editing Guest</h1>

<%= render 'form', guest: @guest %>

<%= link_to 'Show', @guest %> |
<%= link_to 'Back', guests_path %>

app/views/guests/guests_table.js.erb
$('#guests .guests-table').html('<%= guests_table(@guests) %>');

app/views/guests/index.html.erb
<% if @current_user %>
  <%= render partial: "list" %>
<% else %>
  <div id="guests" class="page-section scrollspy">
    <div class="container" >
      <h5 class="center-align">Confirme sua presença</h5>
      <br/>
      <%= text_field_tag 'guest[name]', '', placeholder: 'Digite seu nome aqui' %>
      <div class="guests-table"></div>
    </div>
  </div>
<% end %>

app/views/guests/new.html.erb
<h1>New Guest</h1>

<%= render 'form', guest: @guest %>

<%= link_to 'Back', guests_path %>

app/views/guests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @guest.name %>
</p>

<p>
  <strong>Confirmed:</strong>
  <%= @guest.confirmed %>
</p>

<%= link_to 'Edit', edit_guest_path(@guest) %> |
<%= link_to 'Back', guests_path %>

app/views/index/_cards.html.erb
<div id="cards" class="page-section scrollspy">
  <div class="container" >
      <div class="row">
          <div class="col s12 m4 offset-m2">
            <a target="_blank" href="https://maps.google.com">
              <div class="card hoverable black-text">
                <div class="card-image">
                  <%= image_tag 'map.png' %>
                </div>
                <div class="card-content">
                  <span class="card-title">Localização</span>
                  <p>Salão bem legal na, casa X, rua Y, bairro tal, Brasília, DF </p>
                </div>
              </div>
            </a>
          </div>
          <div class="col s12 m4">
            <a target="_blank" href="http://casamento.casasbahia.com.br/#/lista-presentes/745936">
              <div class="card hoverable black-text">
                <div class="card-image">
                  <%= image_tag 'gift.jpg' %>
                </div>
                <div class="card-content">
                  <span class="card-title">Lista de Presentes</span>
                  <p>Lista de presentes disponivel no site www.lista.com.br</p>
                </div>
              </div>
            </a>
          </div>
      </div>
  </div>
</div>

app/views/index/_gifts.html.erb
<div id="gifts" class="page-section scrollspy">
  <div class="container" style="min-height: 500px"></div>
</div>

app/views/index/_guests.html.erb
<div id="guests" class="page-section scrollspy">
  <div class="container" style="min-height: 500px"></div>
</div>

app/views/index/_history.html.erb
<div id="history" class="page-section scrollspy white-text" style="background: url(<%= image_path 'bg3.jpeg'%>); background-attachment: fixed; background-size: cover;">
  <div class="container center-align text-navigator">
    <ul class="pagination">
      <li class="waves-effect">
        <a href="#!">
          <i class="material-icons history-previous white-text">chevron_left</i>
        </a>
      </li>
      <li>
        <h3 class="text-navigator-title">História não encontrada</h3>
      </li>
      <li class="waves-effect">
        <a href="#!">
          <i class="material-icons history-next white-text">chevron_right</i>
        </a>
      </li>
    </ul>
    <p class="range-field">
      <input type="range" id="history-range" value="0" min="0" max="10" step="1" />
    </p>
    <p class="flow-text text-navigator-content">Não foram encontradas Histórias para serem exibidas aqui! Isso pode ter acontecido por não terem histórias cadastradas no site ou por seu navegador não ser compativel com JavaScript</p>
  </div>
</div>

app/views/index/_honours.html.erb
<div id="honours" class="page-section scrollspy white-text" style="background: url(<%= image_path 'bg2.jpeg'%>); background-attachment: fixed; background-size: cover;">
  <div class="container center-align text-navigator">
    <ul class="pagination">
      <li class="waves-effect">
        <a href="#!">
          <i class="white-text material-icons honour-previous">chevron_left</i>
        </a>
      </li>
      <li>
        <h3 class="text-navigator-title">Homenagem não encontrada</h3>
      </li>
      <li class="waves-effect">
        <a href="#!">
          <i class="white-text material-icons honour-next">chevron_right</i>
        </a>
      </li>
    </ul>
    <p class="range-field">
      <input type="range" id="honour-range" value="0" min="0" max="10" step="1" />
    </p>
    <p class="flow-text text-navigator-content">Não foram encontradas Homenagens para serem exibidas aqui! Isso pode ter acontecido por não terem homenagens cadastradas no site ou por seu navegador não ser compativel com JavaScript</p>
  </div>
</div>

app/views/index/_pictures.html.erb
<div id="pictures" class="page-section scrollspy">
  <div class="container">
      <div class="hide-on-small-only">
        <%= image_tag "carousel/carousel01.jpeg", id:"picture-main", style: 'width: 100%' %>
      </div>
      <div class="owl-carousel owl-theme">
        <% (1..17).each do |index| %>
          <a class="waves-effect hoverable">
            <img class="owl-lazy" data-src="<%= image_path("carousel/carousel#{format('%02d', index)}.jpg") %>" alt="">
          </a>
        <% end %>
      </div>
  </div>
</div>

app/views/index/index.html.erb
<%= render partial: "history" %>
<%= render partial: "pictures" %>
<%= render partial: "honours" %>
<%= render partial: "cards" %>
<%= render template: "guests/index" %>

app/views/layouts/_footer.html.erb
<footer class="page-footer pink darken-4">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Créditos</h5>
        <p class="grey-text text-lighten-4">Framework utilizado:
          <strong>
            <a class="grey-text text-lighten-3" href="http://materializecss.com">Materialize</a>
          </strong>
        </p>
        <p class="grey-text text-lighten-4">Design style:
          <strong>
            <a class="grey-text text-lighten-3" href="https://material.io/">Material Design</a>
          </strong>
        </p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Links</h5>
        <ul>
          <li>
            <a class="grey-text text-lighten-3" href="https://www.facebook.com/luizeduardo.ximenesneto">Facebook</a>
          </li>
          <li>
            <a class="grey-text text-lighten-3" href="<%= rails_admin_path %>">Painel de Administração</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      © 2018 ximenes
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div id="" class="header scrollspy">
  <div class="header-background">
    <div class="parallax-container">
      <div class="parallax">
        <%= image_tag  "bg.jpeg" %>
      </div>
    </div>
  </div>
  <div class="valign-wrapper">
    <div class="content white-text center-align">
      <%= image_tag  "header_image.png" %>
      <h6></h6>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav>
  <div class="nav-wrapper pink darken-4">
    <ul id="nav-mobile" class="left">
      <li>
        <a href="#history">Hitória do casal</a>
      </li>
      <li>
        <a href="#pictures">Fotos</a>
      </li>
      <li>
        <a href="#honours">Homenagens</a>
      </li>
      <li>
        <a href="#cards">Informações</a>
      </li>
      <li>
        <a href="#guests">Confirme sua presença</a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/_rails_data.html.erb
<script>
  var data =  <%= @data.nil? ? '{}' : @data.to_json.html_safe %>;
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jefferson & Marília</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "layouts/header" %>
    <%= render partial: "layouts/navbar" %>
    <div id="page-content" class="page-content">
      <%= yield %>
      <%= render partial: "layouts/footer" %>
    </div>
    <%= render partial: "layouts/rails_data" %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CasamentoMarilliaJefferson</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= render partial: "layouts/rails_data" %>
  </body>
</html>